{ name = "purescript-wags"
, dependencies =
  [ "arrays"
  , "control"
  , "day"
  , "either"
  , "foldable-traversable"
  , "free"
  , "heterogeneous"
  , "identity"
  , "integers"
  , "lists"
  , "math"
  , "maybe"
  , "newtype"
  , "nonempty"
  , "ordered-collections"
  , "prelude"
  , "profunctor-lenses"
  , "psci-support"
  , "record"
  , "sized-vectors"
  , "tuples"
  , "typelevel"
  , "unfoldable"
  , "wags"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs" ]
}
