name: Deploys learn
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/learn
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Spago install
        run: npx spago install
      - name: Spago build
        run: npx spago build
      - name: Webpack build
        run: npm run build
      - name: deploy to netlify
        if: github.ref == 'refs/heads/main'
        run: NETLIFY_SITE_ID=${{ secrets.NETLIFY_LEARN_SITE_ID }} NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify deploy --dir=dist --prod
