name: Deploys hello world
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/hello-world
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Spago install
        run: npx spago install
      - name: Spago build
        run: npx spago build
      - name: Webpack build
        run: npm run build
      - name: mv dist build
        run: mv dist build
      - name: Deploy Netlify
        uses: danakim/gh-action-deploy-netlify@master
        with:
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_ID: ${{ secrets.NETLIFY_HELLO_WORLD_SITE_ID }}
          DEPLOY_PROD: true