name: Unit tests
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Spago install
        run: npx spago -x test.dhall install
      - name: Spago build
        run: npx spago -x test.dhall build
      - name: Spago build examples
        run: npx spago -x examples.dhall build
      - name: Spago test
        run: npx spago -x test.dhall test